# Keep listeners sorted alphabetically.
services:

    etraxis.listener.csrf_token:
        class: AppBundle\EventListener\CsrfToken
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: checkCsrfToken, priority: 15 }
        arguments:
            - "@logger"
            - "@security.csrf.token_manager"

    etraxis.listener.expired_password:
        class: AppBundle\EventListener\ExpiredPassword
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onAction }
        arguments:
            - "@router"
            - "@security.authorization_checker"
            - "@security.token_storage"

    etraxis.listener.sticky_locale:
        class: AppBundle\EventListener\StickyLocale
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: saveLocale }
            - { name: kernel.event_listener, event: kernel.request,             method: setLocale, priority: 10 }
        arguments:
            - "@session"
            - "%locale%"

    etraxis.listener.unauthorized_ajax_request:
        class: AppBundle\EventListener\UnauthorizedAjaxRequest
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onResponse }
        arguments:
            - "@router"
            - "@translator"
            - "@security.authentication_utils"

    etraxis.listener.users_lockout:
        class: AppBundle\EventListener\UsersLockout
        tags:
            - { name: kernel.event_listener, event: security.authentication.success, method: onSuccess }
            - { name: kernel.event_listener, event: security.authentication.failure, method: onFailure }
        arguments:
            - "@logger"
            - "@command_bus"
