parameters:

    database_driver:        pdo_pgsql
    database_host:          127.0.0.1
    database_port:          ~
    database_name:          xe
    database_user:          postgres
    database_password:      ~
    database_charset:       UTF8
